# Generated by Django 6.0.3 on 2026-03-17 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=32, unique=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('color', models.CharField(default='#4ECDC4', max_length=7)),
            ],
            options={
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('color', models.CharField(default='#FF6B6B', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('statement', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('codeforces', 'Codeforces'), ('gfg', 'GeeksForGeeks'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points', models.PositiveIntegerField(default=100)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='problems.problemdifficulty')),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.problemtag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserSolvedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=16)),
                ('submission_id', models.CharField(blank=True, max_length=120)),
                ('solved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('runtime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source_rating_change', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvers', to='problems.problem')),
            ],
            options={
                'ordering': ['-solved_at'],
            },
        ),
    ]
