# Generated by Django 6.0.3 on 2026-03-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersolvedproblem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['platform', 'difficulty'], name='problems_pr_platfor_b1b850_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['title'], name='problems_pr_title_a27f8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('platform', 'external_id'), name='unique_problem_per_platform'),
        ),
        migrations.AddIndex(
            model_name='usersolvedproblem',
            index=models.Index(fields=['user', '-solved_at'], name='problems_us_user_id_83e58b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersolvedproblem',
            index=models.Index(fields=['problem'], name='problems_us_problem_de6b0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersolvedproblem',
            constraint=models.UniqueConstraint(fields=('user', 'problem'), name='unique_solved_problem_per_user'),
        ),
    ]
