# Generated by Django 6.0.3 on 2026-03-20 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('codeforces', 'Codeforces'), ('gfg', 'GeeksForGeeks')], default='leetcode', max_length=16)),
                ('platform_id', models.CharField(default='', max_length=128)),
                ('title', models.CharField(default='', max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProblemTag',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['canonical_name']},
        ),
        migrations.RemoveConstraint(
            model_name='problem',
            name='unique_problem_per_platform',
        ),
        migrations.RemoveConstraint(
            model_name='usersolvedproblem',
            name='unique_solved_problem_per_user',
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_pr_platfor_b1b850_idx',
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_pr_title_a27f8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersolvedproblem',
            name='problems_us_problem_de6b0c_idx',
        ),
        migrations.AddField(
            model_name='problem',
            name='canonical_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersolvedproblem',
            name='language',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='problems.problemdifficulty'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['canonical_name'], name='problems_pr_canonic_ffd1c0_idx'),
        ),
        migrations.AddField(
            model_name='platformproblem',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_problems', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='usersolvedproblem',
            name='platform_problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solvers', to='problems.platformproblem'),
        ),
        migrations.AddConstraint(
            model_name='usersolvedproblem',
            constraint=models.UniqueConstraint(fields=('user', 'platform_problem'), name='unique_solved_problem_per_user'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='acceptance_rate',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='url',
        ),
        migrations.RemoveField(
            model_name='usersolvedproblem',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='usersolvedproblem',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='usersolvedproblem',
            name='source_rating_change',
        ),
        migrations.RemoveField(
            model_name='usersolvedproblem',
            name='submission_id',
        ),
        migrations.AddIndex(
            model_name='platformproblem',
            index=models.Index(fields=['platform', 'platform_id'], name='problems_pl_platfor_cbd93b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformproblem',
            unique_together={('platform', 'platform_id')},
        ),
    ]
