# Generated by Django 6.0.3 on 2026-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_platformproblem_rename_problemtag_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformproblem',
            name='platform',
            field=models.CharField(choices=[('leetcode', 'LeetCode'), ('codeforces', 'Codeforces'), ('gfg', 'GeeksForGeeks'), ('hackerrank', 'HackerRank'), ('custom', 'Custom')], default='leetcode', max_length=16),
        ),
    ]
