# Generated by Codex on 2026-03-23

from django.db import migrations


STANDARD_DIFFICULTIES = {
    "easy": {"name": "Easy", "weight": 1, "color": "#4ECDC4"},
    "medium": {"name": "Medium", "weight": 2, "color": "#FFE66D"},
    "hard": {"name": "Hard", "weight": 3, "color": "#FF6B6B"},
}


def normalize_difficulties_and_stats(apps, schema_editor):
    ProblemDifficulty = apps.get_model("problems", "ProblemDifficulty")
    Problem = apps.get_model("problems", "Problem")
    UserSolvedProblem = apps.get_model("problems", "UserSolvedProblem")
    User = apps.get_model("users", "User")
    ProfileStatistics = apps.get_model("profiles", "ProfileStatistics")

    difficulty_ids = {}
    for slug, payload in STANDARD_DIFFICULTIES.items():
        difficulty, _ = ProblemDifficulty.objects.get_or_create(
            slug=slug,
            defaults={
                "name": payload["name"],
                "weight": payload["weight"],
                "color": payload["color"],
            },
        )
        changed_fields = []
        if difficulty.name != payload["name"]:
            difficulty.name = payload["name"]
            changed_fields.append("name")
        if difficulty.weight != payload["weight"]:
            difficulty.weight = payload["weight"]
            changed_fields.append("weight")
        if difficulty.color != payload["color"]:
            difficulty.color = payload["color"]
            changed_fields.append("color")
        if changed_fields:
            difficulty.save(update_fields=changed_fields)
        difficulty_ids[slug] = difficulty.id

    medium_id = difficulty_ids["medium"]
    Problem.objects.filter(difficulty__isnull=True).update(difficulty_id=medium_id)

    for user in User.objects.all():
        total = UserSolvedProblem.objects.filter(user=user).count()
        easy = UserSolvedProblem.objects.filter(user=user, platform_problem__problem__difficulty__slug="easy").count()
        medium = UserSolvedProblem.objects.filter(user=user, platform_problem__problem__difficulty__slug="medium").count()
        hard = UserSolvedProblem.objects.filter(user=user, platform_problem__problem__difficulty__slug="hard").count()

        ProfileStatistics.objects.update_or_create(
            user=user,
            defaults={
                "total_solved": total,
                "easy_solved": easy,
                "medium_solved": medium,
                "hard_solved": hard,
            },
        )
        user.solved_count = total
        user.save(update_fields=["solved_count"])


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("users", "0006_alter_user_options_and_more"),
        ("problems", "0004_alter_platformproblem_platform"),
    ]

    operations = [
        migrations.RunPython(normalize_difficulties_and_stats, migrations.RunPython.noop),
    ]
