# Generated by Codex on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilestatistics",
            name="challenge_wins",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profilestatistics",
            name="total_challenges",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
