# Generated by Django 6.0.3 on 2026-03-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
