# Generated by Django 6.0.3 on 2026-03-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_country_emailverificationtoken_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
