# Generated by Django 6.0.3 on 2026-03-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codeforces_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gfg_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leetcode_username',
        ),
    ]
