# Generated by Django 6.0.3 on 2026-03-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_codeforces_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="codeforces_username",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gfg_username",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="hackerrank_username",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="leetcode_username",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
