# Generated by Django 6.0.3 on 2026-03-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_integrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-solved_count', '-streak', 'username']},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_rating_e07699_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
