# Generated by Django 6.0.3 on 2026-03-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0002_initial'),
        ('revision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revisionitem',
            name='revision_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='revision.revisionlist'),
        ),
        migrations.AddField(
            model_name='revisionnotes',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_notes', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='revisionnotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='revisionitem',
            unique_together={('revision_list', 'problem')},
        ),
        migrations.AlterUniqueTogether(
            name='revisionnotes',
            unique_together={('user', 'problem')},
        ),
    ]
