# Generated by Django 6.0.3 on 2026-03-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("revision", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RevisionNotes",
            new_name="RevisionNote",
        ),
        migrations.RenameField(
            model_name="revisionnote",
            old_name="notes",
            new_name="note_text",
        ),
        migrations.RemoveField(
            model_name="revisionnote",
            name="memory_hook",
        ),
    ]
