# Generated by Django 6.0.3 on 2026-05-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="integrationstatus",
            new_name="integration_platfor_55573c_idx",
            old_name="integrations_platform_6f8149_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationstatus",
            new_name="integration_user_id_782a81_idx",
            old_name="integrations_user_id_4c7b58_idx",
        ),
    ]
