# Generated by Django 6.0.3 on 2026-03-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_dashboard_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupchallenge',
            new_name='groups_grou_group_i_35b056_idx',
            old_name='groups_group_group_i_7fa622_idx',
        ),
        migrations.AlterField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite Only')], default='invite_only', max_length=16),
        ),
    ]
