# Generated by Django 6.0.3 on 2026-03-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0002_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengeproblem',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_problems', to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='challengeproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_entries', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='challengeresult',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='challengeresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status', '-created_at'], name='challenges__status_c48f5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeproblem',
            unique_together={('challenge', 'problem')},
        ),
        migrations.AlterUniqueTogether(
            name='challengeresult',
            unique_together={('challenge', 'user')},
        ),
    ]
