# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_battle_fields(apps, schema_editor):
    Challenge = apps.get_model("challenges", "Challenge")
    ChallengeProblem = apps.get_model("challenges", "ChallengeProblem")

    status_map = {
        "running": "active",
        "declined": "rejected",
        "expired": "rejected",
    }

    for challenge in Challenge.objects.all():
        if challenge.status in status_map:
            challenge.status = status_map[challenge.status]

        first_problem = (
            ChallengeProblem.objects.filter(challenge_id=challenge.id)
            .select_related("problem")
            .order_by("position", "id")
            .first()
        )
        if first_problem and first_problem.problem_id and challenge.problem_id is None:
            challenge.problem_id = first_problem.problem_id
            challenge.title_snapshot = first_problem.problem.canonical_name
            challenge.statement_snapshot = first_problem.problem.statement or ""
            challenge.constraints_snapshot = "Implement solve(raw_input) and return the final answer as a string."

        challenge.save(
            update_fields=[
                "status",
                "problem",
                "title_snapshot",
                "statement_snapshot",
                "constraints_snapshot",
            ]
        )


def convert_results(apps, schema_editor):
    Challenge = apps.get_model("challenges", "Challenge")
    ChallengeResult = apps.get_model("challenges", "ChallengeResult")

    challenge_ids = ChallengeResult.objects.values_list("challenge_id", flat=True).distinct()
    for challenge_id in challenge_ids:
        results = list(ChallengeResult.objects.filter(challenge_id=challenge_id).order_by("-submitted_at", "-id"))
        if not results:
            continue

        keeper = results[0]
        ChallengeResult.objects.filter(challenge_id=challenge_id).exclude(pk=keeper.pk).delete()
        challenge = Challenge.objects.filter(pk=challenge_id).first()
        if challenge is None:
            continue

        keeper.time_taken = keeper.completion_time_seconds or 0
        keeper.winner_id = challenge.winner_id or keeper.user_id
        if keeper.winner_id == challenge.challenger_id:
            keeper.loser_id = challenge.opponent_id
        elif keeper.winner_id == challenge.opponent_id:
            keeper.loser_id = challenge.challenger_id
        keeper.save(update_fields=["time_taken", "winner", "loser"])


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0005_grouptaskcompletion"),
        ("problems", "0005_normalize_difficulties_and_backfill_stats"),
        ("challenges", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenge",
            old_name="sender",
            new_name="challenger",
        ),
        migrations.RenameField(
            model_name="challenge",
            old_name="receiver",
            new_name="opponent",
        ),
        migrations.RenameField(
            model_name="challenge",
            old_name="started_at",
            new_name="start_time",
        ),
        migrations.RenameField(
            model_name="challenge",
            old_name="finished_at",
            new_name="end_time",
        ),
        migrations.AddField(
            model_name="challenge",
            name="allowed_language",
            field=models.CharField(choices=[("python", "Python")], default="python", max_length=16),
        ),
        migrations.AddField(
            model_name="challenge",
            name="challenger_joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="constraints_snapshot",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="battle_challenges", to="groups.group"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="opponent_joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="problem",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="battle_challenges", to="problems.problem"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="public_test_cases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="challenge",
            name="statement_snapshot",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="test_cases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="challenge",
            name="title_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("active", "Active"), ("finished", "Finished"), ("rejected", "Rejected")], default="pending", max_length=16),
        ),
        migrations.RunPython(populate_battle_fields, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ChallengeSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.TextField()),
                ("language", models.CharField(choices=[("python", "Python")], default="python", max_length=16)),
                ("verdict", models.CharField(choices=[("correct", "Correct"), ("wrong", "Wrong"), ("error", "Error")], default="error", max_length=16)),
                ("execution_time", models.FloatField(default=0.0)),
                ("is_correct", models.BooleanField(default=False)),
                ("time_taken_seconds", models.PositiveIntegerField(default=0)),
                ("output", models.TextField(blank=True)),
                ("error_output", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("challenge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="challenges.challenge")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="challenge_submissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["submitted_at"],
                "indexes": [models.Index(fields=["challenge", "user", "-submitted_at"], name="challenges__challen_5d3507_idx")],
            },
        ),
        migrations.CreateModel(
            name="ChallengeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("tab_switch", "Tab Switch"), ("window_blur", "Window Blur"), ("camera_blocked", "Camera Blocked"), ("camera_enabled", "Camera Enabled")], max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("challenge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="challenges.challenge")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="challenge_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [models.Index(fields=["challenge", "user", "-timestamp"], name="challenges__challen_17754a_idx")],
            },
        ),
        migrations.RenameField(
            model_name="challengeresult",
            old_name="submitted_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="challengeresult",
            name="loser",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lost_battles", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="challengeresult",
            name="time_taken",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="challengeresult",
            name="winner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="won_battles", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="challengeresult",
            name="winning_submission",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="winning_results", to="challenges.challengesubmission"),
        ),
        migrations.RunPython(convert_results, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="challengeresult",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="challengeresult",
            name="completion_time_seconds",
        ),
        migrations.RemoveField(
            model_name="challengeresult",
            name="score",
        ),
        migrations.RemoveField(
            model_name="challengeresult",
            name="solved_count",
        ),
        migrations.RemoveField(
            model_name="challengeresult",
            name="user",
        ),
        migrations.AlterField(
            model_name="challengeresult",
            name="challenge",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="result", to="challenges.challenge"),
        ),
        migrations.AlterField(
            model_name="challengeresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelOptions(
            name="challengeresult",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(fields=["challenger", "status"], name="challenges__challen_79d5a0_idx"),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(fields=["opponent", "status"], name="challenges__opponen_783b17_idx"),
        ),
    ]
