# Generated by Django 6.0.3 on 2026-03-24 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_battle_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenger_camera_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger_camera_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger_camera_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='disqualified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disqualified_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='finish_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('disqualified', 'Disqualified'), ('rejected', 'Rejected')], max_length=32),
        ),
        migrations.AddField(
            model_name='challenge',
            name='opponent_camera_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='opponent_camera_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='opponent_camera_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengeevent',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Blur'), ('camera_blocked', 'Camera Blocked'), ('camera_enabled', 'Camera Enabled'), ('camera_heartbeat', 'Camera Heartbeat')], max_length=32),
        ),
    ]
