# Generated by Django 6.0.3 on 2026-03-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_challenger_camera_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='allowed_language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java')], default='python', max_length=16),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='finish_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('disqualified', 'Disqualified'), ('forfeited', 'Forfeited'), ('rejected', 'Rejected')], max_length=32),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java')], default='python', max_length=16),
        ),
    ]
