# Generated by Django 6.0.3 on 2026-03-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_alter_challenge_allowed_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="public_test_cases",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="test_cases",
        ),
    ]
