# Generated by Django 6.0.3 on 2026-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('challenges_won', models.PositiveIntegerField(default=0)),
                ('contest_points', models.PositiveIntegerField(default=0)),
                ('solved_points', models.PositiveIntegerField(default=0)),
                ('streak_bonus', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['date', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='GlobalLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('total_solved', models.PositiveIntegerField(default=0)),
                ('challenges_won', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank', '-score'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('challenges_won', models.PositiveIntegerField(default=0)),
                ('contest_points', models.PositiveIntegerField(default=0)),
                ('solved_points', models.PositiveIntegerField(default=0)),
                ('streak_bonus', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['week_start', 'rank'],
            },
        ),
    ]
