# Generated by Django 6.0.3 on 2026-03-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rankings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalleaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_leaderboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rankings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyranking',
            unique_together={('date', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyranking',
            unique_together={('week_start', 'user')},
        ),
    ]
