# Generated by Django 6.0.3 on 2026-03-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalleaderboard',
            name='rating',
        ),
    ]
