# Generated by Django 6.0.3 on 2026-03-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0002_initial'),
        ('groups', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestleaderboard',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestleaderboard',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='contests.contestparticipant'),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contestparticipant'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='contestteam',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestteam',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestteam',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_teams', to='groups.group'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contestteam'),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='contests.contestteam'),
        ),
        migrations.AddField(
            model_name='contestleaderboard',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='contests.contestteam'),
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('contest', 'problem')},
        ),
        migrations.AlterUniqueTogether(
            name='contestteam',
            unique_together={('contest', 'name')},
        ),
        migrations.AddIndex(
            model_name='contestsubmission',
            index=models.Index(fields=['contest', 'problem', 'submitted_at'], name='contests_co_contest_788748_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipant',
            unique_together={('contest', 'user')},
        ),
        migrations.AddConstraint(
            model_name='contestleaderboard',
            constraint=models.UniqueConstraint(condition=models.Q(('participant__isnull', False)), fields=('contest', 'participant'), name='unique_contest_participant_board'),
        ),
        migrations.AddConstraint(
            model_name='contestleaderboard',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('contest', 'team'), name='unique_contest_team_board'),
        ),
    ]
